# Generated by Django 4.0.5 on 2022-06-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Direccion',
            field=models.CharField(max_length=300),
        ),
    ]
