# Generated by Django 3.1.2 on 2022-07-06 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220705_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Alimento libre de granos para perros adultos desde 2 a 7 años de razas grandes (25 a 45kg). Con Salmón', max_length=300),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombreProducto',
            field=models.CharField(max_length=80, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='porcDesctoOferta',
            field=models.IntegerField(default=0, verbose_name='Descuento por oferta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='porcDesctoSubscritor',
            field=models.IntegerField(default=0, verbose_name='Descuento subscriptor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
    ]
