# Generated by Django 3.1.2 on 2022-07-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_producto_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='disponible',
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='INGRESAR DESCRIPCION', max_length=300),
        ),
    ]
